/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ro.oradea.ieti.sd;

import org.junit.jupiter.api.Test;

import ro.uoradea.ieti.sd.App;

import static org.junit.jupiter.api.Assertions.*;

import javax.crypto.SecretKey;

class AppTest {
    @Test void decryptionOfEncryptedGivesOriginalMsg() {
        String originalMsg = "acbfed";

        try {
            SecretKey key = App.generateKey();
            String encrypted = App.encrypt(key, originalMsg);
            String decrypted = App.decrypt(key, encrypted);
            assertEquals(originalMsg, decrypted);
        } catch (Exception e) {
            fail(e.getMessage());
        }
    }
}
